/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceAreaRouteImport } from './routes/service-area'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as CommercialIndexRouteImport } from './routes/commercial/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ServicesWaterSoftenersRouteImport } from './routes/services/water-softeners'
import { Route as ServicesWaterLinesRouteImport } from './routes/services/water-lines'
import { Route as ServicesWaterHeatersRouteImport } from './routes/services/water-heaters'
import { Route as ServicesToiletsRouteImport } from './routes/services/toilets'
import { Route as ServicesToiletInstallationRouteImport } from './routes/services/toilet-installation'
import { Route as ServicesSlabLeakRepairRouteImport } from './routes/services/slab-leak-repair'
import { Route as ServicesSepticTankServiceRouteImport } from './routes/services/septic-tank-service'
import { Route as ServicesRepipingRouteImport } from './routes/services/repiping'
import { Route as ServicesPlumbingRouteImport } from './routes/services/plumbing'
import { Route as ServicesPipeReplacementRouteImport } from './routes/services/pipe-replacement'
import { Route as ServicesPipeRepairRouteImport } from './routes/services/pipe-repair'
import { Route as ServicesHydroJettingRouteImport } from './routes/services/hydro-jetting'
import { Route as ServicesHotWaterSystemRepairRouteImport } from './routes/services/hot-water-system-repair'
import { Route as ServicesGasLineRepairRouteImport } from './routes/services/gas-line-repair'
import { Route as ServicesFixtureReplacementRouteImport } from './routes/services/fixture-replacement'
import { Route as ServicesEmergencyPlumberRouteImport } from './routes/services/emergency-plumber'
import { Route as ServicesDrainCleaningRouteImport } from './routes/services/drain-cleaning'
import { Route as ServicesBurstPipeRepairRouteImport } from './routes/services/burst-pipe-repair'
import { Route as CommercialDrainCleaningRouteImport } from './routes/commercial/drain-cleaning'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ServicesSewerServicesIndexRouteImport } from './routes/services/sewer-services/index'
import { Route as ServicesSewerServicesSewerReplacementRouteImport } from './routes/services/sewer-services/sewer-replacement'
import { Route as ServicesSewerServicesSewerRepairRouteImport } from './routes/services/sewer-services/sewer-repair'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreaRoute = ServiceAreaRouteImport.update({
  id: '/service-area',
  path: '/service-area',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialIndexRoute = CommercialIndexRouteImport.update({
  id: '/commercial/',
  path: '/commercial/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWaterSoftenersRoute = ServicesWaterSoftenersRouteImport.update({
  id: '/services/water-softeners',
  path: '/services/water-softeners',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWaterLinesRoute = ServicesWaterLinesRouteImport.update({
  id: '/services/water-lines',
  path: '/services/water-lines',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWaterHeatersRoute = ServicesWaterHeatersRouteImport.update({
  id: '/services/water-heaters',
  path: '/services/water-heaters',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesToiletsRoute = ServicesToiletsRouteImport.update({
  id: '/services/toilets',
  path: '/services/toilets',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesToiletInstallationRoute =
  ServicesToiletInstallationRouteImport.update({
    id: '/services/toilet-installation',
    path: '/services/toilet-installation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSlabLeakRepairRoute = ServicesSlabLeakRepairRouteImport.update({
  id: '/services/slab-leak-repair',
  path: '/services/slab-leak-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSepticTankServiceRoute =
  ServicesSepticTankServiceRouteImport.update({
    id: '/services/septic-tank-service',
    path: '/services/septic-tank-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesRepipingRoute = ServicesRepipingRouteImport.update({
  id: '/services/repiping',
  path: '/services/repiping',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPlumbingRoute = ServicesPlumbingRouteImport.update({
  id: '/services/plumbing',
  path: '/services/plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPipeReplacementRoute = ServicesPipeReplacementRouteImport.update({
  id: '/services/pipe-replacement',
  path: '/services/pipe-replacement',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPipeRepairRoute = ServicesPipeRepairRouteImport.update({
  id: '/services/pipe-repair',
  path: '/services/pipe-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHydroJettingRoute = ServicesHydroJettingRouteImport.update({
  id: '/services/hydro-jetting',
  path: '/services/hydro-jetting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHotWaterSystemRepairRoute =
  ServicesHotWaterSystemRepairRouteImport.update({
    id: '/services/hot-water-system-repair',
    path: '/services/hot-water-system-repair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesGasLineRepairRoute = ServicesGasLineRepairRouteImport.update({
  id: '/services/gas-line-repair',
  path: '/services/gas-line-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesFixtureReplacementRoute =
  ServicesFixtureReplacementRouteImport.update({
    id: '/services/fixture-replacement',
    path: '/services/fixture-replacement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEmergencyPlumberRoute =
  ServicesEmergencyPlumberRouteImport.update({
    id: '/services/emergency-plumber',
    path: '/services/emergency-plumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesDrainCleaningRoute = ServicesDrainCleaningRouteImport.update({
  id: '/services/drain-cleaning',
  path: '/services/drain-cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBurstPipeRepairRoute = ServicesBurstPipeRepairRouteImport.update({
  id: '/services/burst-pipe-repair',
  path: '/services/burst-pipe-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialDrainCleaningRoute = CommercialDrainCleaningRouteImport.update({
  id: '/commercial/drain-cleaning',
  path: '/commercial/drain-cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSewerServicesIndexRoute =
  ServicesSewerServicesIndexRouteImport.update({
    id: '/services/sewer-services/',
    path: '/services/sewer-services/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSewerServicesSewerReplacementRoute =
  ServicesSewerServicesSewerReplacementRouteImport.update({
    id: '/services/sewer-services/sewer-replacement',
    path: '/services/sewer-services/sewer-replacement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSewerServicesSewerRepairRoute =
  ServicesSewerServicesSewerRepairRouteImport.update({
    id: '/services/sewer-services/sewer-repair',
    path: '/services/sewer-services/sewer-repair',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/coupons': typeof CouponsRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/commercial/drain-cleaning': typeof CommercialDrainCleaningRoute
  '/services/burst-pipe-repair': typeof ServicesBurstPipeRepairRoute
  '/services/drain-cleaning': typeof ServicesDrainCleaningRoute
  '/services/emergency-plumber': typeof ServicesEmergencyPlumberRoute
  '/services/fixture-replacement': typeof ServicesFixtureReplacementRoute
  '/services/gas-line-repair': typeof ServicesGasLineRepairRoute
  '/services/hot-water-system-repair': typeof ServicesHotWaterSystemRepairRoute
  '/services/hydro-jetting': typeof ServicesHydroJettingRoute
  '/services/pipe-repair': typeof ServicesPipeRepairRoute
  '/services/pipe-replacement': typeof ServicesPipeReplacementRoute
  '/services/plumbing': typeof ServicesPlumbingRoute
  '/services/repiping': typeof ServicesRepipingRoute
  '/services/septic-tank-service': typeof ServicesSepticTankServiceRoute
  '/services/slab-leak-repair': typeof ServicesSlabLeakRepairRoute
  '/services/toilet-installation': typeof ServicesToiletInstallationRoute
  '/services/toilets': typeof ServicesToiletsRoute
  '/services/water-heaters': typeof ServicesWaterHeatersRoute
  '/services/water-lines': typeof ServicesWaterLinesRoute
  '/services/water-softeners': typeof ServicesWaterSoftenersRoute
  '/blog/': typeof BlogIndexRoute
  '/commercial/': typeof CommercialIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/sewer-services/sewer-repair': typeof ServicesSewerServicesSewerRepairRoute
  '/services/sewer-services/sewer-replacement': typeof ServicesSewerServicesSewerReplacementRoute
  '/services/sewer-services/': typeof ServicesSewerServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/coupons': typeof CouponsRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/commercial/drain-cleaning': typeof CommercialDrainCleaningRoute
  '/services/burst-pipe-repair': typeof ServicesBurstPipeRepairRoute
  '/services/drain-cleaning': typeof ServicesDrainCleaningRoute
  '/services/emergency-plumber': typeof ServicesEmergencyPlumberRoute
  '/services/fixture-replacement': typeof ServicesFixtureReplacementRoute
  '/services/gas-line-repair': typeof ServicesGasLineRepairRoute
  '/services/hot-water-system-repair': typeof ServicesHotWaterSystemRepairRoute
  '/services/hydro-jetting': typeof ServicesHydroJettingRoute
  '/services/pipe-repair': typeof ServicesPipeRepairRoute
  '/services/pipe-replacement': typeof ServicesPipeReplacementRoute
  '/services/plumbing': typeof ServicesPlumbingRoute
  '/services/repiping': typeof ServicesRepipingRoute
  '/services/septic-tank-service': typeof ServicesSepticTankServiceRoute
  '/services/slab-leak-repair': typeof ServicesSlabLeakRepairRoute
  '/services/toilet-installation': typeof ServicesToiletInstallationRoute
  '/services/toilets': typeof ServicesToiletsRoute
  '/services/water-heaters': typeof ServicesWaterHeatersRoute
  '/services/water-lines': typeof ServicesWaterLinesRoute
  '/services/water-softeners': typeof ServicesWaterSoftenersRoute
  '/blog': typeof BlogIndexRoute
  '/commercial': typeof CommercialIndexRoute
  '/services': typeof ServicesIndexRoute
  '/services/sewer-services/sewer-repair': typeof ServicesSewerServicesSewerRepairRoute
  '/services/sewer-services/sewer-replacement': typeof ServicesSewerServicesSewerReplacementRoute
  '/services/sewer-services': typeof ServicesSewerServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/coupons': typeof CouponsRoute
  '/service-area': typeof ServiceAreaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/commercial/drain-cleaning': typeof CommercialDrainCleaningRoute
  '/services/burst-pipe-repair': typeof ServicesBurstPipeRepairRoute
  '/services/drain-cleaning': typeof ServicesDrainCleaningRoute
  '/services/emergency-plumber': typeof ServicesEmergencyPlumberRoute
  '/services/fixture-replacement': typeof ServicesFixtureReplacementRoute
  '/services/gas-line-repair': typeof ServicesGasLineRepairRoute
  '/services/hot-water-system-repair': typeof ServicesHotWaterSystemRepairRoute
  '/services/hydro-jetting': typeof ServicesHydroJettingRoute
  '/services/pipe-repair': typeof ServicesPipeRepairRoute
  '/services/pipe-replacement': typeof ServicesPipeReplacementRoute
  '/services/plumbing': typeof ServicesPlumbingRoute
  '/services/repiping': typeof ServicesRepipingRoute
  '/services/septic-tank-service': typeof ServicesSepticTankServiceRoute
  '/services/slab-leak-repair': typeof ServicesSlabLeakRepairRoute
  '/services/toilet-installation': typeof ServicesToiletInstallationRoute
  '/services/toilets': typeof ServicesToiletsRoute
  '/services/water-heaters': typeof ServicesWaterHeatersRoute
  '/services/water-lines': typeof ServicesWaterLinesRoute
  '/services/water-softeners': typeof ServicesWaterSoftenersRoute
  '/blog/': typeof BlogIndexRoute
  '/commercial/': typeof CommercialIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/sewer-services/sewer-repair': typeof ServicesSewerServicesSewerRepairRoute
  '/services/sewer-services/sewer-replacement': typeof ServicesSewerServicesSewerReplacementRoute
  '/services/sewer-services/': typeof ServicesSewerServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/coupons'
    | '/service-area'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/commercial/drain-cleaning'
    | '/services/burst-pipe-repair'
    | '/services/drain-cleaning'
    | '/services/emergency-plumber'
    | '/services/fixture-replacement'
    | '/services/gas-line-repair'
    | '/services/hot-water-system-repair'
    | '/services/hydro-jetting'
    | '/services/pipe-repair'
    | '/services/pipe-replacement'
    | '/services/plumbing'
    | '/services/repiping'
    | '/services/septic-tank-service'
    | '/services/slab-leak-repair'
    | '/services/toilet-installation'
    | '/services/toilets'
    | '/services/water-heaters'
    | '/services/water-lines'
    | '/services/water-softeners'
    | '/blog/'
    | '/commercial/'
    | '/services/'
    | '/services/sewer-services/sewer-repair'
    | '/services/sewer-services/sewer-replacement'
    | '/services/sewer-services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/coupons'
    | '/service-area'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/commercial/drain-cleaning'
    | '/services/burst-pipe-repair'
    | '/services/drain-cleaning'
    | '/services/emergency-plumber'
    | '/services/fixture-replacement'
    | '/services/gas-line-repair'
    | '/services/hot-water-system-repair'
    | '/services/hydro-jetting'
    | '/services/pipe-repair'
    | '/services/pipe-replacement'
    | '/services/plumbing'
    | '/services/repiping'
    | '/services/septic-tank-service'
    | '/services/slab-leak-repair'
    | '/services/toilet-installation'
    | '/services/toilets'
    | '/services/water-heaters'
    | '/services/water-lines'
    | '/services/water-softeners'
    | '/blog'
    | '/commercial'
    | '/services'
    | '/services/sewer-services/sewer-repair'
    | '/services/sewer-services/sewer-replacement'
    | '/services/sewer-services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/coupons'
    | '/service-area'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/commercial/drain-cleaning'
    | '/services/burst-pipe-repair'
    | '/services/drain-cleaning'
    | '/services/emergency-plumber'
    | '/services/fixture-replacement'
    | '/services/gas-line-repair'
    | '/services/hot-water-system-repair'
    | '/services/hydro-jetting'
    | '/services/pipe-repair'
    | '/services/pipe-replacement'
    | '/services/plumbing'
    | '/services/repiping'
    | '/services/septic-tank-service'
    | '/services/slab-leak-repair'
    | '/services/toilet-installation'
    | '/services/toilets'
    | '/services/water-heaters'
    | '/services/water-lines'
    | '/services/water-softeners'
    | '/blog/'
    | '/commercial/'
    | '/services/'
    | '/services/sewer-services/sewer-repair'
    | '/services/sewer-services/sewer-replacement'
    | '/services/sewer-services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CouponsRoute: typeof CouponsRoute
  ServiceAreaRoute: typeof ServiceAreaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CommercialDrainCleaningRoute: typeof CommercialDrainCleaningRoute
  ServicesBurstPipeRepairRoute: typeof ServicesBurstPipeRepairRoute
  ServicesDrainCleaningRoute: typeof ServicesDrainCleaningRoute
  ServicesEmergencyPlumberRoute: typeof ServicesEmergencyPlumberRoute
  ServicesFixtureReplacementRoute: typeof ServicesFixtureReplacementRoute
  ServicesGasLineRepairRoute: typeof ServicesGasLineRepairRoute
  ServicesHotWaterSystemRepairRoute: typeof ServicesHotWaterSystemRepairRoute
  ServicesHydroJettingRoute: typeof ServicesHydroJettingRoute
  ServicesPipeRepairRoute: typeof ServicesPipeRepairRoute
  ServicesPipeReplacementRoute: typeof ServicesPipeReplacementRoute
  ServicesPlumbingRoute: typeof ServicesPlumbingRoute
  ServicesRepipingRoute: typeof ServicesRepipingRoute
  ServicesSepticTankServiceRoute: typeof ServicesSepticTankServiceRoute
  ServicesSlabLeakRepairRoute: typeof ServicesSlabLeakRepairRoute
  ServicesToiletInstallationRoute: typeof ServicesToiletInstallationRoute
  ServicesToiletsRoute: typeof ServicesToiletsRoute
  ServicesWaterHeatersRoute: typeof ServicesWaterHeatersRoute
  ServicesWaterLinesRoute: typeof ServicesWaterLinesRoute
  ServicesWaterSoftenersRoute: typeof ServicesWaterSoftenersRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CommercialIndexRoute: typeof CommercialIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesSewerServicesSewerRepairRoute: typeof ServicesSewerServicesSewerRepairRoute
  ServicesSewerServicesSewerReplacementRoute: typeof ServicesSewerServicesSewerReplacementRoute
  ServicesSewerServicesIndexRoute: typeof ServicesSewerServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-area': {
      id: '/service-area'
      path: '/service-area'
      fullPath: '/service-area'
      preLoaderRoute: typeof ServiceAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial/': {
      id: '/commercial/'
      path: '/commercial'
      fullPath: '/commercial/'
      preLoaderRoute: typeof CommercialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/water-softeners': {
      id: '/services/water-softeners'
      path: '/services/water-softeners'
      fullPath: '/services/water-softeners'
      preLoaderRoute: typeof ServicesWaterSoftenersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/water-lines': {
      id: '/services/water-lines'
      path: '/services/water-lines'
      fullPath: '/services/water-lines'
      preLoaderRoute: typeof ServicesWaterLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/water-heaters': {
      id: '/services/water-heaters'
      path: '/services/water-heaters'
      fullPath: '/services/water-heaters'
      preLoaderRoute: typeof ServicesWaterHeatersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/toilets': {
      id: '/services/toilets'
      path: '/services/toilets'
      fullPath: '/services/toilets'
      preLoaderRoute: typeof ServicesToiletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/toilet-installation': {
      id: '/services/toilet-installation'
      path: '/services/toilet-installation'
      fullPath: '/services/toilet-installation'
      preLoaderRoute: typeof ServicesToiletInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/slab-leak-repair': {
      id: '/services/slab-leak-repair'
      path: '/services/slab-leak-repair'
      fullPath: '/services/slab-leak-repair'
      preLoaderRoute: typeof ServicesSlabLeakRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/septic-tank-service': {
      id: '/services/septic-tank-service'
      path: '/services/septic-tank-service'
      fullPath: '/services/septic-tank-service'
      preLoaderRoute: typeof ServicesSepticTankServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/repiping': {
      id: '/services/repiping'
      path: '/services/repiping'
      fullPath: '/services/repiping'
      preLoaderRoute: typeof ServicesRepipingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/plumbing': {
      id: '/services/plumbing'
      path: '/services/plumbing'
      fullPath: '/services/plumbing'
      preLoaderRoute: typeof ServicesPlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/pipe-replacement': {
      id: '/services/pipe-replacement'
      path: '/services/pipe-replacement'
      fullPath: '/services/pipe-replacement'
      preLoaderRoute: typeof ServicesPipeReplacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/pipe-repair': {
      id: '/services/pipe-repair'
      path: '/services/pipe-repair'
      fullPath: '/services/pipe-repair'
      preLoaderRoute: typeof ServicesPipeRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hydro-jetting': {
      id: '/services/hydro-jetting'
      path: '/services/hydro-jetting'
      fullPath: '/services/hydro-jetting'
      preLoaderRoute: typeof ServicesHydroJettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hot-water-system-repair': {
      id: '/services/hot-water-system-repair'
      path: '/services/hot-water-system-repair'
      fullPath: '/services/hot-water-system-repair'
      preLoaderRoute: typeof ServicesHotWaterSystemRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/gas-line-repair': {
      id: '/services/gas-line-repair'
      path: '/services/gas-line-repair'
      fullPath: '/services/gas-line-repair'
      preLoaderRoute: typeof ServicesGasLineRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/fixture-replacement': {
      id: '/services/fixture-replacement'
      path: '/services/fixture-replacement'
      fullPath: '/services/fixture-replacement'
      preLoaderRoute: typeof ServicesFixtureReplacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/emergency-plumber': {
      id: '/services/emergency-plumber'
      path: '/services/emergency-plumber'
      fullPath: '/services/emergency-plumber'
      preLoaderRoute: typeof ServicesEmergencyPlumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/drain-cleaning': {
      id: '/services/drain-cleaning'
      path: '/services/drain-cleaning'
      fullPath: '/services/drain-cleaning'
      preLoaderRoute: typeof ServicesDrainCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/burst-pipe-repair': {
      id: '/services/burst-pipe-repair'
      path: '/services/burst-pipe-repair'
      fullPath: '/services/burst-pipe-repair'
      preLoaderRoute: typeof ServicesBurstPipeRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial/drain-cleaning': {
      id: '/commercial/drain-cleaning'
      path: '/commercial/drain-cleaning'
      fullPath: '/commercial/drain-cleaning'
      preLoaderRoute: typeof CommercialDrainCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sewer-services/': {
      id: '/services/sewer-services/'
      path: '/services/sewer-services'
      fullPath: '/services/sewer-services/'
      preLoaderRoute: typeof ServicesSewerServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sewer-services/sewer-replacement': {
      id: '/services/sewer-services/sewer-replacement'
      path: '/services/sewer-services/sewer-replacement'
      fullPath: '/services/sewer-services/sewer-replacement'
      preLoaderRoute: typeof ServicesSewerServicesSewerReplacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sewer-services/sewer-repair': {
      id: '/services/sewer-services/sewer-repair'
      path: '/services/sewer-services/sewer-repair'
      fullPath: '/services/sewer-services/sewer-repair'
      preLoaderRoute: typeof ServicesSewerServicesSewerRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CouponsRoute: CouponsRoute,
  ServiceAreaRoute: ServiceAreaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  CommercialDrainCleaningRoute: CommercialDrainCleaningRoute,
  ServicesBurstPipeRepairRoute: ServicesBurstPipeRepairRoute,
  ServicesDrainCleaningRoute: ServicesDrainCleaningRoute,
  ServicesEmergencyPlumberRoute: ServicesEmergencyPlumberRoute,
  ServicesFixtureReplacementRoute: ServicesFixtureReplacementRoute,
  ServicesGasLineRepairRoute: ServicesGasLineRepairRoute,
  ServicesHotWaterSystemRepairRoute: ServicesHotWaterSystemRepairRoute,
  ServicesHydroJettingRoute: ServicesHydroJettingRoute,
  ServicesPipeRepairRoute: ServicesPipeRepairRoute,
  ServicesPipeReplacementRoute: ServicesPipeReplacementRoute,
  ServicesPlumbingRoute: ServicesPlumbingRoute,
  ServicesRepipingRoute: ServicesRepipingRoute,
  ServicesSepticTankServiceRoute: ServicesSepticTankServiceRoute,
  ServicesSlabLeakRepairRoute: ServicesSlabLeakRepairRoute,
  ServicesToiletInstallationRoute: ServicesToiletInstallationRoute,
  ServicesToiletsRoute: ServicesToiletsRoute,
  ServicesWaterHeatersRoute: ServicesWaterHeatersRoute,
  ServicesWaterLinesRoute: ServicesWaterLinesRoute,
  ServicesWaterSoftenersRoute: ServicesWaterSoftenersRoute,
  BlogIndexRoute: BlogIndexRoute,
  CommercialIndexRoute: CommercialIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesSewerServicesSewerRepairRoute: ServicesSewerServicesSewerRepairRoute,
  ServicesSewerServicesSewerReplacementRoute:
    ServicesSewerServicesSewerReplacementRoute,
  ServicesSewerServicesIndexRoute: ServicesSewerServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
